### PR TITLE
Fix backwards compatibility issue with React Fragments

### PR DESCRIPTION
**Pull request by chadfawcett**
`React.Fragments` is not supported by all the React versions this package supports.

### CODE REVIEW

**Comment by itsdanielmatos** [comment]
Hey @chadfawcett what a catch 🦅👁! When I created this PR #37 I did not realize the react version dependency.

I checked your PR and the changes are pretty straight to the point :+1:. **Note** that using `React.Fragment`we are able to group a list of children without adding extra nodes to the DOM.

**Before** this PR the outcome was one of the following: 
```
<div>
    {children}
</div>
```
 or 
```
<div>
    {children}
    {cropmarks}
</div>
```
**With this PR** when crop marks are enabled the outcome is the following (we add an extra dom node):
```
<div>
    {children}
    <div>
        {cropmarks}
    </div>
</div>
```

IMHO, it makes sense since we are grouping the crop marks in a parent container. I just tested and everything works as expected :100:.

@philcockfield can you provide some feedback :+1: ?

**Comment by chadfawcett** [comment]
@itsdanielmatos Yeah, I like React.Fragment for it's use case. I just figured going back to the extra DOM element was a better fix than dropping support for React ^0.14.7 and ^15.0.0. The styles didn't break either with the extra DOM element, which was my only concern.

**Comment by philcockfield** [comment]
Sounds good - thanks a ton @chadfawcett.

**Comment by philcockfield** [comment]
Published to version: `storybook-host@5.0.3`

**Pull request merged**
